channels:
- uibcdf/label/dev
- uibcdf
- conda-forge
- ambermd
- defaults
dependencies:
- pyunitwizard
- pandas
- mdtraj
- mdanalysis
- nglview
- plip
- matplotlib
- networkx
- rdkit
- requests
- scikit-learn
- tqdm
- chembl_webresource_client
