channels:
- uibcdf/label/dev
- uibcdf
- conda-forge
- ambermd
- defaults
dependencies:
- pyunitwizard
- pandas
- openmm
- mdtraj
- mdanalysis
- nglview
- matplotlib
- networkx
- rdkit
- requests
- tqdm
