production:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - uibcdf_stdlib
    - pyunitwizard
    - molsysmt
    - openmm
    - nglview
    - matplotlib

development:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - uibcdf_stdlib
    - pyunitwizard
    - molsysmt
    - openmm
    - jupyterlab
    - nglview
    - matplotlib
    - pytest
    - pip
    - pytest-cov
    - codecov
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

test:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - uibcdf_stdlib
    - pyunitwizard
    - molsysmt
    - openmm
    - nglview
    - matplotlib
    - pytest
    - pip
    - pytest-cov
    - codecov

docs:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - uibcdf_stdlib
    - pyunitwizard
    - molsysmt
    - openmm
    - nglview
    - matplotlib
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables
    - jupyterlab

setup:
  channels:
    - defaults
  dependencies:
    - setuptools
    - numpy
    - versioneer

conda-build:
  channels:
    - conda-forge
    - defaults
  dependencies:
    - anaconda-client
    - conda-build

