package:
  name: openpharmacophore
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy 
    - versioneer

  run:
    - python
    - numpy
    - pyunitwizard
    - pandas
    - mdtraj
    - mdanalysis
    - nglview
    - plip
    - matplotlib
    - rdkit
    - requests
    - scikit-learn
    - tqdm


about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    A library to work with pharmacophores.
  dev_url: https://github.com/uibcdf/OpenPharmacophore
  doc_url: https://uibcdf.org/OpenPharmacophore
