package:
  name: openpharmacophore
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - pyunitwizard
  - pandas
  - mdtraj
  - mdanalysis
  - nglview
  - plip
  - matplotlib
  - rdkit
  - requests
  - scikit-learn
  - tqdm
  - pip:
    - chembl_webresource_client==0.10.7
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'A library to work with pharmacophores.

    '
  dev_url: https://github.com/uibcdf/openpharmacophore
  doc_url: https://uibcdf.org/openpharmacophore
